package cd.precheck.sql;

/**
 * 用于确认 7.5.1.6 渠道佣金类月报 存储过程是否可以运行.
 * 
 * @author Administrator
 * 
 */
public class M_3g_7_5_1_6_sql {

	/**
	 * 下面的校验针对7.5.1.6 渠道佣金类月报 的所有存储过程.
	 * 
	 * MID.MID_M_BUSI_MOBILEUSER
	 * MID.MID_M_INTELLIGENTUSER_PPS
	 * MID.MID_M_COMMISION_LIST_EXT
	 * MID.MID_M_USER_OWE_BILL
	 * MID.MID_M_V_USER_MOBILEUSER_3G_ZD
	 * MID.MID_M_USER_CHARGE_SECOND_HOR
	 * 
	 */
	//MID.MID_M_V_USER_MOBILEUSER_3G_ZD
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_01 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_V_USER_MOBILEUSER_3G_ZD' AND LOGDATE=?";
	//MID.MID_M_USER_CHARGE_SECOND_HOR
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_02 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_USER_CHARGE_SECOND_HOR' AND LOGDATE=?";
	//MID.MID_M_BUSI_MOBILEUSER
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_03 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_BUSI_MOBILEUSER' AND LOGDATE=?";
	//MID.MID_M_INTELLIGENTUSER_PPS
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_04 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_INTELLIGENTUSER_PPS' AND LOGDATE=?";
	//MID.MID_M_COMMISION_LIST_EXT
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_05 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_COMMISION_LIST_EXT' AND LOGDATE=?";
	//MID.MID_M_USER_OWE_BILL
	public static final String PRECHECK_REPORT_P_ZB_CHANNEL_M_3G_06_02_06 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_USER_OWE_BILL' AND LOGDATE=?";
	
}
