package cd.precheck.sql;

/**
 * 用于确认 7.5.1.4 渠道数量类月报 存储过程是否可以运行.
 * 
 * @author Administrator
 * 
 */
public class M_3g_7_5_1_4_sql {

	/**
	 * 下面的校验针对7.5.1.4 渠道数量类月报 的所有存储过程.
	 * 
	 * MID.MID_M_INCO_CHARGE_MONTH
	 * MID.MID_M_F_DEV_USER_3G
	 * MID.MID_M_3G_USER
	 * MID.MID_M_COMMISION_LIST_EXT
	 * MID.MID_M_USER_CHARGE_SECOND_HOR
	 * MID.MID_M_V_USER_MOBILEUSER_3G_ZD
	 * 
	 */
	//MID.MID_M_V_USER_MOBILEUSER_3G_ZD
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_01 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_V_USER_MOBILEUSER_3G_ZD' AND LOGDATE=?";
	//MID.MID_M_USER_CHARGE_SECOND_HOR
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_02 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_USER_CHARGE_SECOND_HOR' AND LOGDATE=?";
	//MID.MID_M_COMMISION_LIST_EXT
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_03 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_COMMISION_LIST_EXT' AND LOGDATE=?";
	//MID.MID_M_3G_USER
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_04 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_3G_USER' AND LOGDATE=?";
	//MID.MID_M_F_DEV_USER_3G
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_05 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_F_DEV_USER_3G' AND LOGDATE=?";
	//MID.MID_M_INCO_CHARGE_MONTH
	public static final String PRECHECK_REPORT_P_ZB_M_3G_CHANNEL_XX_06 = "SELECT * FROM MID.MID_T_LOG WHERE UPPER(procname) = 'MID.P_MID_M_INCO_CHARGE_MONTH' AND LOGDATE=?";
	
}
